CREATE TABLE exames (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nome VARCHAR(200) NOT NULL,
    descricao VARCHAR(500),
    categoria VARCHAR(100),
    tipo_amostra ENUM('SANGUE', 'URINA', 'FEZES', 'OUTRO') NOT NULL,
    prazo_dias INT NOT NULL,
    valor DECIMAL(10, 2),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
);
